### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by wl935** [tianchen101/DeepAR#1]
Could you please upload the dataset 'LD2011_2014.txt' used in the codes?

Cheers.

**Comment by tianchen101** [comment]
Hi,
 Sorry the dataset is too large and cannot be uploaded to github, the data
is UCI utility usage data,
The link is here:
https://archive.ics.uci.edu/ml/datasets/ElectricityLoadDiagrams20112014#

**Comment by wl935** [comment]
Thanks a lot.
